apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-secret
  namespace: argocd
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sre-bootcamp-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/atharva-kulkarni123/SRE-BootCamp.git
        username: atharva-kulkarni123
        password: "{{ .ARGOCD_SECRET | toString }}"   # ← add toString
  data:
    - secretKey: ARGOCD_SECRET
      remoteRef:
        key: database
        property: pat-token
