apiVersion: v1
kind: Service
metadata:
  name: web-application-service
  namespace: student-api-ns
  labels:
    app: web-application-service
spec:
  type: {{ .Values.appservice.type }}
  selector:
    app: web-application
  ports:
  - name: http
    port: {{ .Values.appservice.port }}
    targetPort: {{ .Values.appservice.targetport }}
    nodePort: {{ .Values.appservice.nodePort }}