apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  namespace: student-api-ns
  labels: 
    app: web-application
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:             
      app: web-application
  template:       
    metadata:
      labels:
        app: web-application 
    spec:
      nodeSelector:
        role: app
      containers:
      - name: web-application
        image: atharvak2427/updated-student-api:{{ .Values.app.imageTag }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.appservice.containerPort }}
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:  
                name: app-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_PORT
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_USER
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_NAME
          - name: FLASK_ENV
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: FLASK_ENV
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DB_PASSWORD
          - name: DATABASE_URL
            value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"