apiVersion: v1
kind: Service
metadata:
  name: web-application-service
  namespace: application
spec:
  type: {{ .Values.appservice.type }}
  selector:
    app: web-application
  ports:
  - port: {{ .Values.appservice.port }}
    targetPort: {{ .Values.appservice.targetport }}
    nodePort: {{ .Values.appservice.nodePort }}