apiVersion: v2
name: monitoring
description: Prometheus + Grafana monitoring stack for students-api
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: "58.7.2"
    repository: https://prometheus-community.github.io/helm-charts
