kube-prometheus-stack:
  grafana:
    enabled: true
    nodeSelector:
      app: monitoring

    adminPassword: admin

    service:
      type: NodePort
      nodePort: 32000

  prometheus:
    enabled: true

    prometheusSpec:
      nodeSelector:
        app: monitoring

  alertmanager:
    enabled: false

    alertmanagerSpec:
      nodeSelector:
        app: monitoring

  kube-state-metrics:
    nodeSelector:
      app: monitoring

  prometheus-node-exporter:
    nodeSelector:
      app: monitoring

  prometheusOperator:
    nodeSelector:
      app: monitoring