apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policy
  namespace: monitoring
  labels:
    grafana_alert: "1"
data:
  notification-policy.yaml: |
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: email-alerts
        groupBy:
          - alertname
          - namespace
          - pod
        groupWait: 30s
        groupInterval: 5m
        repeatInterval: 4h