apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: students-api-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - application
  selector:
    matchLabels:
      app: web-application-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s