apiVersion: v2
name: hashicorp-vault
description: Install HashiCorp Vault
type: application
version: 0.1.0
appVersion: "1.20.0"

dependencies:
  - name: vault
    version: "0.30.0"
    repository: "https://helm.releases.hashicorp.com"
  - name: external-secrets
    version: 0.20.4
    repository: https://charts.external-secrets.io